-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 15:59:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema si-13-02-18
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema si-13-02-18
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `si-13-02-18` DEFAULT CHARACTER SET utf8 ;
USE `si-13-02-18` ;

-- -----------------------------------------------------
-- Table `si-13-02-18`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`Role` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(10) NULL DEFAULT 'Client',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`User` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(20) NULL,
  `Mail` VARCHAR(255) NULL,
  `Birthday` DATE NULL,
  `Civility` TINYINT NULL,
  `Height` FLOAT NULL,
  `Weight` FLOAT NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role_idx` (`Role_id` ASC),
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_id`)
    REFERENCES `si-13-02-18`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`Destination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`Destination` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`Destination` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PlanetName` VARCHAR(45) NULL,
  `Time` INT NULL,
  `Distance` FLOAT NULL,
  `Price` INT NULL,
  `Image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`Reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Place` INT(3) NULL DEFAULT 300,
  `Destination_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reservation_Destination1_idx` (`Destination_id` ASC),
  INDEX `fk_Reservation_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Reservation_Destination1`
    FOREIGN KEY (`Destination_id`)
    REFERENCES `si-13-02-18`.`Destination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `si-13-02-18`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
