-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 11:24:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema si-13-02-18
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema si-13-02-18
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `si-13-02-18` DEFAULT CHARACTER SET utf8 ;
USE `si-13-02-18` ;

-- -----------------------------------------------------
-- Table `si-13-02-18`.`date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`date` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`date` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`destination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`destination` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`destination` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `PlanetName` VARCHAR(45) NULL DEFAULT NULL,
  `Time` INT(11) NULL DEFAULT NULL,
  `Distance` FLOAT NULL DEFAULT NULL,
  `Price` INT(11) NULL DEFAULT NULL,
  `Image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`lieu` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`lieu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Lieu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`role` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(10) NULL DEFAULT 'Client',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`user` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `FirstName` VARCHAR(20) NULL DEFAULT NULL,
  `Mail` VARCHAR(255) NULL DEFAULT NULL,
  `Birthday` DATE NULL DEFAULT NULL,
  `Civility` TINYINT(4) NULL DEFAULT NULL,
  `Height` FLOAT NULL DEFAULT NULL,
  `Weight` FLOAT NULL DEFAULT NULL,
  `Role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role_idx` (`Role_id` ASC),
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_id`)
    REFERENCES `si-13-02-18`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `si-13-02-18`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `si-13-02-18`.`reservation` ;

CREATE TABLE IF NOT EXISTS `si-13-02-18`.`reservation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Destination_id` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  `lieu_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reservation_Destination1_idx` (`Destination_id` ASC),
  INDEX `fk_Reservation_User1_idx` (`User_id` ASC),
  INDEX `fk_reservation_lieu1_idx` (`lieu_id` ASC),
  CONSTRAINT `fk_Reservation_Destination1`
    FOREIGN KEY (`Destination_id`)
    REFERENCES `si-13-02-18`.`destination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `si-13-02-18`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_lieu1`
    FOREIGN KEY (`lieu_id`)
    REFERENCES `si-13-02-18`.`lieu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `role` (Name) VALUES ('Admin'),('Client');
INSERT INTO `destination` VALUES (1,'Moon',1,356626,404,'moon-transparent.png'),(2,'Mars',4,356626,1000,'mars-transparent.png'),(3,'Mercury',8,211251000,2400,'mercury-transparent.png'),(4,'Venus',3,12112400,800,'venus-transparent.png'),(5,'Xenion 500',22,12414400,5555,'xenion500-transparent.png'),(6,'Europe',15,2141210143,3500,'europe-transparent.png');
INSERT INTO `lieu` VALUES (1,'Cosmodrome de Baïkonour'),(2,'Base de lancement de Cap Canaveral'),(3,'Centre spatial guyanais'),(4,'Base de lancement de Tanegashima'),(5,'Base de lancement de Sohae');
INSERT INTO `date` VALUES (1,'2052-05-17'),(2,'2083-07-23'),(3,'2032-08-01'),(4,'2150-10-25'),(5,'2999-12-31'),(6,'2873-04-01');